version: "3.8"
services:
    backend:
        container_name: backend
        build: 
            context: ./server
        ports: 
            - "3002:3002"
        restart: always
        volumes:
            - ./server:/usr/src/app/src
        # links:
            # - mongo
        depends_on:
            - cache
            # - mongo

    frontend:
        container_name: frontend
        build:
            context: ./client
        ports:
            - "3000:3000"
        restart: always
        volumes:
            - ./client/src:/usr/src/app/src

    cache:
        image: redis:6.2-alpine  

    
volumes:
    cache:
        driver: local